# Generated by Django 4.1.7 on 2023-02-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_service_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.TextField(blank=True)),
                ('slug', models.TextField(unique=True)),
                ('stock', models.CharField(choices=[('In stock', 'In stock'), ('Out of stock', 'Out of stock')], max_length=100)),
                ('label', models.CharField(blank=True, choices=[('Hot', 'Hot'), ('New', 'New'), ('Sale', 'Sale'), ('', 'default')], max_length=100)),
                ('rank', models.IntegerField(null=True)),
            ],
        ),
    ]
