# Generated by Django 4.1.7 on 2023-02-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_about_delete_information'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
