# Generated by Django 4.1.7 on 2023-02-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
